### ISSUE TITLE
Add constraints

### ISSUE THREAD

**Issue by nicholasjackson** [hashicorp/faas-nomad#18]
Add the ability to add a constraint to a function to restrict the architecture for a function:

```yaml
provider:  
  name: faas
  gateway: http://localhost:8080

functions:  
  ipconfig:
    image: alexellis/windows-ipconfig:nano
    skip_build: true
    environment:
      suppress_lock: true
    constraints:
      - "node.platform.os == windows"
```

In this instance the function would only be deployed to a node running windows
