### ISSUE TITLE
Limited Ability to use Vault Secrets.

### ISSUE THREAD

**Issue by ryanmickler** [hashicorp/faas-nomad#60]
I've been trying to integrate openfaas-nomad into our stack, but a lot of our functions require access to various AWS S3 buckets to read/write data. The problem is that the openfaas-nomad vault integration only can access secrets at `secrets/${secrets_dir}/${secret_name}`. However, for our AWS secrets, we'd need to read secrets at `aws/creds/${secrets_name}`. Can i propose that we include the ability to customize this vault policy, instead of `VaultDefaultPolicy: "openfaas"`

Secondly, it would also be required to be able to specify the template that is rendered, as each read of the aws secrets generates a new set of two keys that need to be rendered simultaneously. The default template format
`{{with secret "secret/${vault_prefix}/${secret_name}"}}{{.Data.${name}}}{{end}}`
isn't suitable for this purpose. 

So i propose that we also provide the ability to specify the policy and pass in a template block 

```
functions:
  facedetect:
    lang: go-opencv
    handler: ./facedetect
    image: nicholasjackson/func_facedetect
    secrets:
      - mysecret 
        vault_policy: my_s3_secret_vault_policy
        template: |
[default] {{with secret "aws/creds/my_s3_secret"}}
aws_access_key_id={{.Data.access_key}}
aws_secret_access_key={{.Data.secret_key}}{{end}}
```

the vault policy `my_s3_secret_vault_policy` would just allow read access to `aws/creds/my_s3_secret`.

This example would generate a suitable AWS_CREDENTIALS_FILE at `\etc\openfaas\secrets\mysecret` that could be used to provide AWS api access.

**Comment by ryanmickler** [comment]
Thanks for the quick reply. However, after looking through the openfaas-nomad source, i believe that my desired functionality could be accomplished entirely within this repo, without having to modify the core openfaas source.

The only modifications would be to the openfaas function definition yaml, but including the `vault_policy` and `template` strings.

In fact, i believe it could only be done in this repo, as we'd need to directly interact with the nomad API.

**Comment by acornies** [comment]
Hi Ryan, thanks for opening this issue. I think part of what you're asking for is already implemented:
`vault_default_policy` and `vault_secret_path_prefix ` can be overridden. However, there are no function-specific overrides and it does currently expect this template format:

```
{{with secret "%s"}}{{.Data.%s}}{{end}}
```
translates
```
{{with secret "vault_secret_path_prefix"}}{{.Data.mysecret}}{{end}}
```

My plan was to implement function-specific overrides for this exact purpose, but it would take the form of adding annotations to a function rather than change the behaviour of secrets in the faas-cli.

**Comment by ryanmickler** [comment]
hmmm. im not sure how the annotations to a function would work, but it sounds interesting. But you are spot on, a function-specific override of `vault_default_policy `, `vault_secret_path_prefix`, and the template would satisfy my use case. Its just a question of how that would be specified.

**Comment by acornies** [comment]
My idea was this:
```
functions:
  facedetect:
    lang: go-opencv
    handler: ./facedetect
    image: nicholasjackson/func_facedetect
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    annotations:
      vault_policy: my_s3_secret_vault_policy
      vault_path_prefix: aws/creds
```
this would get you what you want using openfaas' standard format for secrets. I'll have to think on how to specific a whole secret template so that it gels nicely with the rest of that faas ecosystem.

**Comment by ryanmickler** [comment]
Furthermore, for injecting multiple secrets, you'd want at least to have a separate `vault_path_prefix` per secret. And probably have a separate `vault_policy` too, however thats not a critical requirement.

**Comment by ryanmickler** [comment]
Yeah, however, just for a bit of future proofing, we want to inject two secrets that require separate custom templates. Is there no way to embed the extra data (policy, template) as a child of the ‘secret’ node in the yaml without violating the openfaas standards for secrets, as in my original post? I think using these annotations seems confusing.

**Comment by ryanmickler** [comment]
I was going to suggest something pretty much identical to this solution. This would meet my use case. Thanks!

**Comment by ryanmickler** [comment]
So can i suggest just a slight modification to your solution
```
functions:
  facedetect:
    lang: go-opencv
    handler: ./facedetect
    image: nicholasjackson/func_facedetect
    secrets:
      - mysecret 
    annotations:
        vault_policy_mysecret: my_s3_secret_vault_policy
        vault_template_mysecret: |
[default] {{with secret "aws/creds/my_s3_secret"}}
aws_access_key_id={{.Data.access_key}}
aws_secret_access_key={{.Data.secret_key}}{{end}}
```

The template file will be rendered to `/etc/openfaas/secrets/mysecret`. This seems to be a bit cleaner.
