### ISSUE TITLE
com.openfaas.scale.max and com.openfaas.scale.min have no impact on the minimum and maximum number of replicas

### ISSUE THREAD

**Issue by hxalid** [hashicorp/faas-nomad#61]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Deploy OpenFaaS on an existing Nomad cluster
2. Create and deploy a simple function as 

```
provider:
  name: faas
  gateway: https://openfaas-gateway

functions:
  bcrypt:
    lang: go
    handler: ./bcrypt
    image: "<myregistry>/faas-bcrypt:1.0.0"
    labels:
      datacenters: "dev"
      com.openfaas.scale.min: "2"
      com.openfaas.scale.max: "5"
      com.openfaas.scale.factor: "20"
      com.openfaas.scale.zero: true
    environment:
        read_timeout: 20s
        write_timeout: 20s
        write_debug: true
```

3. Load test using some tools, such as Vegeta, to increase the number of replicas.

What happens?
It goes up to 20

What were you expecting to happen?
It should not go beyond com.openfaas.scale.max, which is 5.

Any logs, error output, etc?
----------------------------
```
curl -s https://openfaas-gateway/system/function/bcrypt   | jq
{
  "name": "bcrypt",
  "image": "",
  "invocationCount": 0,
  "replicas": 1,
  "envProcess": "",
  "availableReplicas": 1,
  "labels": null,
  "annotations": null
}


curl -s https://openfaas-gateway/system/functions   | jq
[
  {
    "name": "bcrypt",
    "image": "<myregistry>/faas-bcrypt:1.0.0",
    "invocationCount": 10,
    "replicas": 1,
    "envProcess": "",
    "availableReplicas": 0,
    "labels": {
      "com.openfaas.scale.factor": "20",
      "com.openfaas.scale.max": "5",
      "com.openfaas.scale.min": "2",
      "com.openfaas.scale.zero": "true",
      "datacenters": "dev"
    },
    "annotations": null
  }
]
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:**
Ubuntu 16.04

**OpenFaaS Version:** …
```
"version": {
    "commit_message": "Add OpenFest and IstaCon events in November",
    "sha": "b1d1fe21e0c54611715f8eac611ca98134a342f6",
    "release": "dev"
  }
```
**Nomad Version:** …
Nomad v0.8.6
